---
title: "R Notebook"
output:
  html_notebook: default
editor_options:
  chunk_output_type: inline
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, 
                      eval = TRUE, 
                      message = FALSE, warning = FALSE)
#set include to false to only include chunks we're building from beginning

library(here)
here() #here is now set to your root directory with .Rproj file

library(tidyverse)
library(janitor)
library(data.table)
library(skimr)
library(here)
library(readxl)

#install.packages("googlesheets4)
library(googlesheets4)

#install.packages("skimr")
library(airportr)
```


# Load data from Google Sheets 

```{r load-data}
#from Excel 
# here()
# coral_travel <- read_excel("2018-raw-data-from-Sam-01302020-for-teagan.xlsx",
#                            na = "NA") %>% 
#   clean_names()

#load from Google Sheets
# coral_travel_original <- 
#   read_sheet("https://docs.google.com/spreadsheets/d/1bbf_4Uv9diOOovP5iAgWFFdf-VZfSIkAqk_m0eH78a4/edit#gid=134456861") %>% 
#   clean_names()
#   
# coral_travel_original
# names(coral_travel_original)
# nrow(coral_travel_original)
# 
# length(unique(coral_travel_original$article_id)) #104 articles in 2018 
# 
# #export cleaner database - one line per article
# complete_data <- coral_travel_original %>% 
#  select(article_id, 
#         journal, 
#         affiliation, 
#         affiliation_country,
#         affiliation_airport, 
#         affiliation_airport_code, 
#         field_study_location, 
#         field_country, 
#         field_airport, 
#         field_airport_code) %>% 
#   na.omit() %>% 
#   distinct()
# 
# complete_data
# 
# #update some airport codes
# complete_data %>% 
#   filter(str_detect(affiliation, "Lucia"))
# 
# complete_data %>% 
#   filter(str_detect(field_study_location, "Moorea"))
# 
# #clean up
# complete_data <- complete_data %>% 
#   mutate(affiliation_airport_code = 
#            case_when(
#              str_detect(affiliation, "Woods") ~ "BOS", 
#              str_detect(affiliation, "St Lucia") ~ "BNE",
#              TRUE ~ affiliation_airport_code), 
#          field_airport_code = 
#            case_when(
#              str_detect(field_study_location, "Moorea") ~ "PPT", 
#              TRUE ~ field_airport_code))
# 
# #75 complete rows with airport codes
# complete_data %>% 
#   fwrite(here("data", 
#               "data for analysis.csv"))

coral_travel <- read_csv(here("data", "data for analysis.csv"))

coral_travel
names(coral_travel)
skim(coral_travel)
```


#Some summaries 

```{r summaries}
#count distinct articles
coral_travel %>%
  distinct(article_id) %>% 
  nrow()
#75 unique articles

#count distinct journals
coral_travel %>%
  distinct(journal) %>% 
  nrow()
#9 journals

#range of number of articles per journal
# coral_travel%>%
#   select(journal,article_id) %>% 
#   nchar(., type = "chars", allowNA = FALSE, keepNA = NA)

#total number of routes
coral_travel %>%
  select(affiliation_airport,field_airport) %>%
  count()
#75 routes

#count distinct/unique routes
coral_travel %>%
  select(affiliation_airport,field_airport)%>%
  distinct() %>% 
  arrange(affiliation_airport,field_airport) %>% 
  count()
#67 distinct routes

#Number of different start airports
coral_travel%>%
  distinct(affiliation_airport)%>%
  count()
#47 distinct start airports

#number of different end airports
coral_travel%>%
  distinct(field_airport)%>%
  count()
#51 distinct end airports

#number of different field locations
coral_travel%>%
  distinct(field_study_location)%>%
  count()
#60 distinct field locations not sure how to discern ecoregion look up different package?

```


# Find distance between airport codes

```{r find-travel-distance}
#step 1 testing apply function for each column
# trial_travel <- coral_travel_original %>% 
#   filter(!is.na(affiliation_airport)) %>%
#   select(field_airport_code, affiliation_airport_code)
# 
# trial_travel

# #distance function applied down columns = total km 
# f = function(x,output) {
#     # x is the row of type Character
#     # access element in first column
#     affiliation_airport_code = x[1]
#     # access element in second column
#     field_airport_code = x[3]
#     #your code to process x
#     airport_distance(affiliation_airport_code, field_airport_code)
# }
# 
# apply(trial_travel, 2, f)
# 
# #distance function applied across rows = km per route 
# f = function(x,output) {
#     # x is the row of type Character
#     # access element in first column
#     affiliation_airport_code = x[1]
#     # access element in second column
#     field_airport_code = x[3]
#     #your code to process x
#     airport_distance(affiliation_airport_code, field_airport_code)
# }
# 
# apply(trial_travel, 1, f) 

#Check 
coral_travel$affiliation_airport_code[1]
coral_travel$field_airport_code[1]
airport_distance(coral_travel$affiliation_airport_code[1], coral_travel$field_airport_code[1])

#add new column with airport distances between each pair
#??airport_lookup  
#airportr::airport_lookup("HBA", output_type = "city")
??airportr::airport_distance

## 1 - distance using airportr distances, km
coral_travel <- coral_travel %>% 
  rowwise() %>%  
  mutate(airport_distance_km = airportr:::airport_distance(affiliation_airport_code, field_airport_code)) #single route

skim(coral_travel$airport_distance)

#some examples of the furthest distances
coral_travel %>% 
  filter(airport_distance_km > 10000) %>% 
  select(article_id, 
         contains("code"), 
         contains("country"), 
         airport_distance_km) %>% 
  arrange(-airport_distance_km)
```
#Distance to carbon emissions
https://sheilasaia.rbind.io/post/2019-04-19-carbon-cost-calcs/

And then compare to an equivalencies calculator 
https://www.epa.gov/energy/greenhouse-gas-equivalencies-calculator

```{r distance-to-carbon}

#1 - distance to carbon, 1:1 conversion
#convert km to miles
#units -  metric tons of carbon dioxode
num_people <- 1

coral_travel <- coral_travel %>% 
  mutate(distance_miles = airport_distance_km * 0.621, 
         co2_distance = (distance_miles * num_people * 0.24 * (1 / 2204.62) * 1.891), 
         co2_distance_roundtrip = co2_distance *2)

sum(coral_travel$co2_distance_roundtrip) #80 metric tonnes

ggplot(coral_travel, 
       aes(airport_distance_km , co2_distance)) + 
  geom_point() + 
  theme_minimal()


#2 - distance to carbon based on flight duration
#https://media.nature.com/original/magazine-assets/d41586-020-02057-2/18168996

#Short-haul flight 400-1,500km 200 gCO2e / km / person]
#Long-haul flight 1,500-8,000 250 gCO2e / km / person] 
#Super long-haul flight >8,000 300 gCO2e / km / person]

coral_travel <- coral_travel %>% 
  mutate(co2_category = case_when(
    airport_distance_km > 0 & airport_distance_km < 1500 ~ 200 * airport_distance_km, 
    airport_distance_km >= 1500 & airport_distance_km < 8000 ~ 250 * airport_distance_km, 
    airport_distance_km >= 8000 ~ 300 * airport_distance_km), 
    co2_category = co2_category * (1/1000000), 
    co2_category_roundtrip = co2_category * 2)

sum(coral_travel$co2_category_roundtrip, na.rm = TRUE)
  

```